### ISSUE TITLE
Exercice 3.26

### ISSUE THREAD

**Issue by wissam124** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#10]
Shouldn't it be p(s',r|s,a)\*[r + \gamma v_{\*}(s\)] under the sum? 
See eq. 3.20 from the book.

**Comment by LyWangPX** [comment]
Yes, though I think you have a typo, you mean p(s',r|s,a)*[r + \gamma v_{*}(s')] under the sum right? There is a missing prime symbol.

Fixed.

**Comment by wissam124** [comment]
Yes, it is indeed s'
