### ISSUE TITLE
Solution for problem 3.4

### ISSUE THREAD

**Issue by kiran4you** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#13]
Hi, 
For problem 3.4 : 
according to equation 3.3 the sum probabilities has to be one. but i see in the solution they are not coming to one. Do we need to normalise them with a factor? If my understanding of equation 3.3 is wrong, then what probabilities will be summed to one for this problem? 

Uday

**Comment by wissam124** [comment]
Hi,

You are not looking at it correctly, you shouldn't just sum all of the p(s', r|s, a).

What the formula says is that, for a given fixed pair (s, a) the probabilities over the pairs s', a should sum up to 1. 

So, for example, if we take the pair (s='high, a='search'), the possibilities for p(s', r|s, a) are \alpha and 1 - \alpha which do sum up to one.

What you need to understand is that we have conditional probabilities, i.e. a distribution over S x R for each pair (s, a).

**Comment by LyWangPX** [comment]
Thanks for wissam's answer. That is what I am going to say.
