### ISSUE TITLE
Exercise 6.11

### ISSUE THREAD

**Issue by qihuazhong** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#17]
Some of the statements in the current solution are misleading.

It states that 
"...because it does not take the current policy into consideration at all. Any policy will choose A from S, and Q learning will always evaluate the states using greedy method..."

This is not true, especially for the first part.  The current policy matters because it guides the behaviour and affects which states will be visited. I have the impression that the original answer made that statement thinking A is fixed for Q(S, A) anyway so the current policy does not matter. But this is a faulty logic (Any action value methods like Sarsa will also be off-policy following this logic).

The key to a correct explanation is to distinguish between a behaviour policy and the target policy. The former guides the agent as to which action will be taken (or sampled in a broader sense), and the later is the one used for updates. When these two policies are the same, then it is a on-policy method.

In the case of Q-learning. The behaviour could be an epsilon greedy (or others), and the target policy is always greedy.

This video has great explanation: https://www.coursera.org/lecture/sample-based-learning-methods/how-is-q-learning-off-policy-1OikH

**Comment by LyWangPX** [comment]
I apologize for the misleading part. What I did want to say is during the evaluation part, where the algorithm decides to update the policy, the current policy does not matter. I did not make it clear. I beilive though, we are talking about the same issue. 

Thanks for pointing out the ambiguous wording and I will fix it. I will put the name of you on readme.md in return.
