### ISSUE TITLE
exercise 10.2

### ISSUE THREAD

**Issue by SHITIANYU-hue** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#18]
hello,

In this problem, why not consider \pi(a|s_{t+1})?
As in text book, it looks like this:

<img width="710" alt="Screen Shot 2020-03-07 at 2 14 43 PM" src="https://user-images.githubusercontent.com/38762389/76151003-0557b000-607e-11ea-910f-383118cbadc0.png">

**Comment by LyWangPX** [comment]
Thanks for pointing out.  You are right, it's a mistake. 
It should have the same answer as on page 259.
I will update the answer and label your work.
