### ISSUE TITLE
Ex 5.11

### ISSUE THREAD

**Issue by qihuazhong** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#19]
<img width="485" alt="Screen Shot 2020-03-08 at 10 07 06 PM" src="https://user-images.githubusercontent.com/22231207/76177012-2822bb00-6189-11ea-9bae-1b6d46b4a653.png">

The target policy \pi is indeed deterministic and greedy. However, I think the answer can be improved with the following clarification:

- A_t is action generated using the behaviour policy (often epsilon soft with respect to 
![image](https://user-images.githubusercontent.com/22231207/76178467-d92b5480-618d-11ea-9631-3c3783f7119b.png) BEFORE update)
- ![image](https://user-images.githubusercontent.com/22231207/76177508-d713c680-618a-11ea-98a9-6a9818eb419b.png) is the greedy action after the update. 

One is epsilon soft with old Q, the other is deterministic greedy with new Q. They actually do not necessarily equal each other. However, when these two are not equal, we exit the episode, do NOT update W, and proceed to the next episode. Therefore, 
![image](https://user-images.githubusercontent.com/22231207/76177835-cdd72980-618b-11ea-9fef-edc6d05824d1.png) is always one. (we discard the episode when it is not).

<img width="535" alt="Screen Shot 2020-03-08 at 10 10 39 PM" src="https://user-images.githubusercontent.com/22231207/76178000-463dea80-618c-11ea-9df9-0d50a1e227e9.png">

To understand this better, we need to acknowledge that the off-policy MC control updates happen only after the whole episode finishes. And the updates proceed from the end of the episode and go backwards (loop for t = T-1, T-2, ... 0). This is actually a problem with Off-policy MC control: it only learns from the tails of episodes when all of the remaining actions in the episode are greedy.  This makes it a very inefficient off-policy method.

**Comment by LyWangPX** [comment]
Thanks for the kind response. I agree with the problem you mentioned in your reply and I am glad you write your understandings about MC. Yes, MC at this stage is really shallow. Sometimes I believe the idea of reaching the end of game like MC is a great method but should be taken inside a more general algorithm like MC tree. This notion will be mentioned again as 'rollout' later, (or maybe you have read the later chapters), which will consider the issue more thoroughly.

Regarding to the problem, I think I did overgeneralize the answer a little bit. I will add the connection to mention A_t is the action being allowed to change W, which means A_t is the choice of pi as always.
