### ISSUE TITLE
Ex 6.5

### ISSUE THREAD

**Issue by qihuazhong** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#20]
<img width="470" alt="Screen Shot 2020-03-09 at 9 29 40 PM" src="https://user-images.githubusercontent.com/22231207/76270858-1efb2200-624d-11ea-8912-ed78a210117e.png">

The first point is valid: alpha is not small enough. But the second point is not relevant. The 'down and up again' behaviour of the error is caused by the initialization value of 0.5, which is exactly the true value of the state c. This means during the first few episodes when state c is not updated yet, it has the 0 error. But once it gets updated, the estimated value for state c will fluctuate around the true value for state c but not very close (the higher alpha, the more fluctuating).

Therefore,  the initialization of exactly 0.5 causes the down and up again phenomenon. 

The following figure empirically demonstrates situations when states are initialized with a different value. It's clear only 0.5 initialization has this issue.
![image](https://user-images.githubusercontent.com/22231207/76273936-946af080-6255-11ea-9980-0c08d6a1d65e.png)

If we break down the squared error of each state a,b,c,d and e (all initialized with 0.5) over training episodes, it again shows state c is the cause.

![image](https://user-images.githubusercontent.com/22231207/76274266-92556180-6256-11ea-883a-655a00b9433a.png)

**Comment by LyWangPX** [comment]
Very impressive idea.

Would you like to explain a little bit more? In your first graph, at episode 20, somehow we reach the optimal point and then the cost rises. However, in the second graph, state c is increasing its SE in first few episodes but almost get flattened around episode 20. It seems have no difference with others. It alone does not compensate the rise of MSE in the first graph. 

If you can give me a graph which breaks downs the Delta Cost, it will be much clearer to me. 

The late half of my original answer is based on the random initialization of deep learning. I cannot see any reason why we do initialization with no randomness. If you can give me more ideas on this part, it will be helpful too.

My current belief stands between my original answer and yours. Somehow I think maybe the state c has chain effect to all other states, especially b and d.

Looking forward to your response.

**Comment by qihuazhong** [comment]
you raised a very good question. the error for state c is the cause, but itself alone cannot fully explain the behaviour. My suspicion is this: since this is TD(0), or in other words one step bootstrapping. That means the error for state c will also play a role for state b and e (b bootstrap from estimates of a and c, etc...), and then the same idea for a and e with a smaller effect from c

That in turns will mean the error for state b and state d will also go up a little bit, as the error for c goes up from 0 to where it should be. This causes a lasting effect beyond episode 20.

I should replace the second graph with RMSE so it is more visible:

![image](https://user-images.githubusercontent.com/22231207/76340118-6b884100-62d1-11ea-9c2d-77c2686c30fd.png)

this graph actually gives a lot of interesting observations.
1) The error for state b and state d also increases a little after episode 20. Although not very obvious
1) The error for state a and state e is consistently lower than other states. The reason is that state a bootstrap from state left absorbing state and state b (bootstrap one step from either left or right). The absorbing state can be viewed to have 0 error. Therefore the resulting error for state a is less than the error for other states. The same logic goes for state e.

 
The TD error (delta, which measures the difference between the current estimate and a "better" estimate after seeing a new smaple) gives a clear look on the lasting effect:

![image](https://user-images.githubusercontent.com/22231207/76340727-6f689300-62d2-11ea-824a-2e02fad081e6.png)


About random initialization:

This is a rather rare situation, for this to happen we need some specific conditions, notable ones are:
1. the initialization value of state c is very close to its true value
2. the average of initialization value of state b and state d is very close to  the true value of c (this will slow down the fluctuation of the estimated value of state c at the beginning!)

Now, we can add some noise to the initialization, I tried a random initialization of uniformly from [0.45, 0.55]. We get very similar results, but with a smaller scale.

![image](https://user-images.githubusercontent.com/22231207/76341886-097d0b00-62d4-11ea-8cdc-e830b5625a69.png)


![image](https://user-images.githubusercontent.com/22231207/76341904-0f72ec00-62d4-11ea-98c0-d94b129566f6.png)


![image](https://user-images.githubusercontent.com/22231207/76341916-1437a000-62d4-11ea-852e-2dca3d960dc4.png)


I also tried with a larger range of randomness: [0.3, 0.7]. The 'down and up' effect is almost gone. I suspect because condition 1) is broken.


![image](https://user-images.githubusercontent.com/22231207/76342470-08001280-62d5-11ea-8bb2-cdb0bffa17fc.png)

![image](https://user-images.githubusercontent.com/22231207/76342483-0cc4c680-62d5-11ea-939c-1b3a9392c681.png)

![image](https://user-images.githubusercontent.com/22231207/76342495-10f0e400-62d5-11ea-8486-b92529395e27.png)


* all results are from 100 runs with different seeds.

**Comment by qihuazhong** [comment]
Just did some further experiments:

I randomly initialized state a and state b from [0, 0.5], but initialize state d and e in a way so that (b+d)/2 = 0.5, (a+e)/2=0.5. This makes sure condition 2) is satisfied.

Tried this while initializing c with [0.3, 0.5, 0.6, 0.7], this allow us the examine the effect of condiction 
1. 

The results show actually condition 2 is more important.

![image](https://user-images.githubusercontent.com/22231207/76344895-b5c0f080-62d8-11ea-88c9-891d752ba5d2.png)

observations:
- The 'down and up' effect is more obvious. (since a and b are randomly initialized between [0, 0.5], this is closer to their true values compared to 0.5 initialization. It takes less time to converge to their true value. Therefore the 'down and up' happens earlier and deeper)
- initialization of c doesn't matter much, as long as (b+d)/2 =0.5 and (a+e)/2 =0.5


![image](https://user-images.githubusercontent.com/22231207/76345226-531c2480-62d9-11ea-97d6-3b78ffc411f3.png)


![image](https://user-images.githubusercontent.com/22231207/76345236-57e0d880-62d9-11ea-9b1a-eb98a5ae4dca.png)

**Comment by LyWangPX** [comment]
Very deep and interesting results.I still have a few extending questions.

1.  As you mention, I agree the early drop can also be a sign that the dynamic of the system is too easy to get the true convergence at early stage. I am curious what will happen we do the opposite: give the wrong initialization but keep the linearity. For example, a and b from [0.5,1] and d and e from [0,0.5]. Another interesting idea would be a and c from [0,0.5] and d and e from [0.5,1]. If such zigzag does not affect the early drop, your assumption is robust.

2. Do you think this phenomenon, though interesting, is totally harmless? I think it does not affect the final accuracy at all. It is definitely different from Deep Learning literature where an 'early stop' can benefit. What do you think?

3. Do you think, the phenonmenon is limited to the case where the true state values are lineraly related, e.g., all on a straight line? What if the coincidence of linearity of TD method and the linearity of the true state vaues, is one of important reasons why the symmtry initialization will occur problem? (Though some of them need 1 to be confirmed)

It feels exciting and full of joy to talk with another intelligent mind on this matter. I am looking forward to your reply.

PS: Your work will be cited in the original pdf after discussion. And due to the effort you have done, your name will appear in pdf as the author.

**Comment by qihuazhong** [comment]
It is exciting to have an in-depth discussion. I am glad you didn't take my solution at face value and close the issue. 

Upon more experiments, I found the causes are different than I originally thought. I will need to dig into this further. But I really need to focus on my midterm exam for the coming days. So please keep the issue open and I will come back later one this.

**Comment by LyWangPX** [comment]
Of course! I have a few interviews to prepare so good luck to us both! I will keep the issue open.

**Comment by LyWangPX** [comment]
I will close it for now for inactivity. 
If any progress is made on ths problem, I will reopen it.

**Comment by ehddnr747** [comment]
Thanks for very impressive discussion here!
