### ISSUE TITLE
Ex 10.6 & 10.7

### ISSUE THREAD

**Issue by qihuazhong** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#21]
I believe that the answer posted for 10.6 is actually for 10.7, and vice versa. Unless we are reading different versions of the book (I am using the second edition available online).

**Comment by LyWangPX** [comment]
I did a quick check. 
Yep you are right. Somehow I messed up the sequence when I move my draft to overleaf.
Will fix it. Thank you !
