### ISSUE TITLE
Exercise 12.13

### ISSUE THREAD

**Issue by enakai00** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#24]
Hi, I uploaded the solution of Exercise 12.13.

http://enakai00.hatenablog.com/entry/2019/07/07/111353

**Comment by LyWangPX** [comment]
Thanks for your kind response and I will review them later.

**Comment by LyWangPX** [comment]
Closed for the TBA of chapter 12.
