### ISSUE TITLE
Exercise 3.19

### ISSUE THREAD

**Issue by Qcaria** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#31]
Hi, I think that one has to multiply the value of node s' (v_\pi (s')) by the discounting factor gamma. Thank you for your work, it is helping me a lot!

**Comment by LyWangPX** [comment]
I will check it out in a min.
Thanks for pointing it out!

**Comment by LyWangPX** [comment]
Fixed. Thank you!
