### ISSUE TITLE
ex 11.2 typo

### ISSUE THREAD

**Issue by tomasruizt** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#43]
Hi :) you may want to complete in the first line the q function with the missing action:
`q(S, w)` to `q(S, A, w)`.

The next is just nitpicking, but if you want to harmonize the notation with the book, then the approximation of V is written in lowercase and with hat instead of bar. 

Cheers :)

**Comment by LyWangPX** [comment]
That's a valid point. Thanks.
I got some other similar advices and I may update them altogether in the near future.
