### ISSUE TITLE
exercise 5.6 

### ISSUE THREAD

**Issue by Hyperion-shuo** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#44]
![image](https://user-images.githubusercontent.com/55169296/80459878-a0c21e80-8965-11ea-92b7-cf1f40eaee9e.png)

Seems there is no need to do importance sampling for action on step t.

**Comment by Hyperion-shuo** [comment]
The subscript of the importance sampling ratio should start at t+1.
Because you already assume take action At so there is no need to multiply the ratio for action t, just like there is no importance sampling rate in DQN.
This answer maybe helpful : https://www.reddit.com/r/reinforcementlearning/comments/b2e0xr/why_no_importance_sampling_in_dqn/

**Comment by LyWangPX** [comment]
Yep you are right.
I will fix it. Thank you.
