### ISSUE TITLE
Ex.3.9 error

### ISSUE THREAD

**Issue by HERIUN** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#49]
your term has some mistakes.. check this..
https://yashbonde.github.io/blogs/bartosutton/chap3_ex.html
but, under sigma k must be 0.

**Comment by LyWangPX** [comment]
Looks like I forgot to include the reward inside the sum. 
Thanks for the report. I will fix it asap.

**Comment by HERIUN** [comment]
I find another missing on that site. 
https://yashbonde.github.io/blogs/bartosutton/chap3_ex.html
fix G1 term gamma^k

**Comment by LyWangPX** [comment]
My current answer is correct. 
The answer you refer is subtly wrong. 
Please revisit the formula of geometric series and the definition of G.
The issue will not be reopened.
