### ISSUE TITLE
ex4.5 solution modification

### ISSUE THREAD

**Issue by alphabetsean** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#56]
Hi, in Policy Improvement of ex4.5, isn't is more clear and succinct to update the policy by selecting the action with maximum q value for every state? such as following:

policy_stable <- true
For each s \in S:
    old_action <- \pi (s)
    \pi(s) <- argmax_{a} q(s,a)
......(same as original solution)

**Comment by LyWangPX** [comment]
If multiple actions are of same highest q values, breaking ties would cause action choice being changed every time step and potentially make the loop forever. That’s the aim of my solution.

**Comment by Quoding** [comment]
I think the suggested modification is valid in the sense that it prevents from looping for every state-action pair and just looping over states. Argmax does the job of "looping" over every action anyway and therefore removes some complexity (in the sense of understanding) from the loop itself.

I'm not expert, so I may be wrong.
