### ISSUE TITLE
Exercise 5.3

### ISSUE THREAD

**Issue by NishanthARao** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#59]
Could you please provide the backup diagram for exercise 5.3 i.e., the backup diagram for Q\pi ?
I wanted to check if it's right, and I could find it nowhere else.

Like could you draw it on a paper and attach the scanned image in chapter 5 folder?

Thank you so much.

**Comment by LyWangPX** [comment]
It would be super long straight line until you hit the end.
Please refer to Figure 7.3 on page 146.
