### ISSUE TITLE
ex 10.6 and 10.7 don't match book

### ISSUE THREAD

**Issue by dipplestix** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#60]
10.6 and 10.7 don't seem to match the question in the book, will file a PR with updated solutions

**Comment by LyWangPX** [comment]
Please refer to RL2020, which is the latest pdf version. http://incompleteideas.net/book/RLbook2020.pdf
The old version has different questions which is more confusing than the updated one. You probably have the old one.

**Comment by LyWangPX** [comment]
If you still find the question not aligned, report a new issue. Thanks.
