### ISSUE TITLE
Ch 10 Ex. 10.6

### ISSUE THREAD

**Issue by KimMatt** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#64]
Hi I'm currently going through the exercises for this book as well: https://github.com/KimMatt/RL_Projects

In your solution to 10.6 how did you get from 

<img src="https://render.githubusercontent.com/render/math?math=E[R_{t+1}|S_0=s] - r(\pi)">
to 
<img src="https://render.githubusercontent.com/render/math?math=\frac{-1^t}{2}">
?

**Comment by LyWangPX** [comment]
Hi there, I think expanding the reward series and minus the average reward would result to this. By the way, the book updated 10.6 and 10.7 and exchanged them. Please make sure you are using the newest one.

Cheer

**Comment by KimMatt** [comment]
Ok thanks. Gonna have another crack at it
