### ISSUE TITLE
Clarification Ex 4.5_ Deterministic Policy

### ISSUE THREAD

**Issue by Avalpreet** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#66]
2. Policy Evaluation:
Since the policy pi is deterministic, shouldn't the 
_sigma_a' pi(a'|s') Q(s',a') be replaced with Q(s', pi(s')) ?

**Comment by LyWangPX** [comment]
pi is deterministic, that’s true. The environment is not necessarily. So I keep the original sigma there for completeness.

**Comment by Avalpreet** [comment]
Thanks for the clarification
