### ISSUE TITLE
Ex 4.7-A

### ISSUE THREAD

**Issue by Avalpreet** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#67]
Line 151 : pi[(i, j)] = 0
Why are all pi[(i,j)] initialized to 0???

Shouldn't pi[(i,j)] -> a  ??
i.e., randomly mapped to actions in set A = {-5,-4,-3,-2,-1, 0, 1,2,3,4,5}

**Comment by LyWangPX** [comment]
It is welcomed to bring your solutions since this is a...terrified early script I randomly wrote at best. I can rewrite one but I think you could do that too. 

If your proposal makes the entire script works, I can do the update.

**Comment by Avalpreet** [comment]
Thanks for the response
