### ISSUE TITLE
Exercise 4.8

### ISSUE THREAD

**Issue by Levin-2020** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#69]
In the first part of your answer you said that there would be a 0.5 probability of winning if our capital is at 50. That is not true, we actually have a 0.4 probability of winning, because the given problem defines the probability of the coin coming up heads as ph = 0.4. You can also see it in the Graph above.
It's only a minor detail, but I still wanted to point it out in case somebody is confused by it.

**Comment by LyWangPX** [comment]
Thanks for pointing it out. You are right.
Let me correct it in a minute.
