### ISSUE TITLE
Exercise 4.5

### ISSUE THREAD

**Issue by Kaniee** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#71]
The update rule for Q(s, a) is written as if the policy would be stochastic, but instead it is deterministic (in this setup)
So the term as the sum over all a' should be replaced with Q(s', \pi(s')).

**Comment by LyWangPX** [comment]
You are right. Though it is little bit trivial so I would correct it with other ones later.
