### ISSUE TITLE
Exercise 6.1

### ISSUE THREAD

**Issue by Kaniee** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#72]
I think u<sub>t</sub> is defined incorrect.

If we use u<sub>t+1</sub> in the third row, then it must be
u<sub>t</sub> = α [R<sub>t+1</sub> + γ V<sub>**t-1**</sub> (S<sub>t+1</sub>) - V<sub>**t-1**</sub> (S<sub>t</sub>).

Alternatively we could use u<sub>t</sub> in the there row and therefore
u<sub>t</sub> = α [R<sub>t+**2**</sub> + γ V<sub>t</sub> (S<sub>t+**2**</sub>) - V<sub>t</sub> (S<sub>t+**1**</sub>).

This is due to the TD update, which is
V<sub>t+1</sub> (S<sub>t</sub>) = V<sub>t</sub> (S<sub>t</sub>) + α [R<sub>t+1</sub> + γ V<sub>t</sub> (S<sub>t+1</sub>) - V<sub>t</sub> (S <sub>t</sub>)]
and therefore
V<sub>t+1</sub> (S<sub>t+1</sub>) = V<sub>t</sub> (S<sub>t+1</sub>) + α [R<sub>t+2</sub> + γ V<sub>t</sub> (S<sub>t+2</sub>) - V<sub>t</sub> (S<sub>t+1</sub>)].

**Comment by LyWangPX** [comment]
Sorry for the late reply. I write the definition of u_t but I used it as u_t+1 so everything there should be incremented.
