### ISSUE TITLE
Exercise 3.28

### ISSUE THREAD

**Issue by NakuraMino** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#73]
Why is there no decay term? Is there a reason why it doesn't become (r + gamma * v_*(s'))?

**Comment by XinArkh** [comment]
Same question. I think maybe the author forgot to type it.

**Comment by LyWangPX** [comment]
You guys are right, I forgot it :) Will patch tonight.

**Comment by NakuraMino** [comment]
Thanks!
