### ISSUE TITLE
Exercise 2.3

### ISSUE THREAD

**Issue by ShaowuChen** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#87]
It may be Q_{k+1}=Q_k + \alpha_{k}(R_k-Q_k},
instead of Q_{k+1}=Q_k + \alpha_{k+1}(R_{k+1}-Q_k},
because the logic is when t=k, choose action A_t, get reward R_k, then update Q_{k+1}.

**Comment by LyWangPX** [comment]
Thanks for pointing it out. It has been added to the error log and will be updated in the next version.
