### ISSUE TITLE
Exercice 3.24

### ISSUE THREAD

**Issue by wissam124** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#9]
Small comment

You've already given the answer in 3.10 for the geometric sum so there's no need to write any code (but I suppose always useful to know how to do a quick loop in Python!) 

The result is simply \frac{10}{1-\gamma^{5})

**Comment by LyWangPX** [comment]
You are right. I will add the theoretical answer as well.
